name: Dependency License Check

on:
  push:
    branches:
      - main

jobs:
  license_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
  
    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

    # - name: Build and generate license reports
    #   run: |
    #     mvn license:third-party-report
    #     mv target report

    # - name: Store license reports as artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: license-reports
    #     path: ./report/site/

    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: imeshdocker
        password: imesh@docker

    - name: Docker Build & Push
      if: success()
      run: |
        docker build . -t imeshdocker/dep-check:${SHORT_SHA}
        docker push imeshdocker/dep-check:${SHORT_SHA}

    - name: Install Trivy
      uses: aquasecurity/trivy@v0.44.0  # You can replace this version with the latest available
      with:
        image-ref: alpine  # Choose the base image for Trivy scanning (alpine is used here as an example)

    - name: Trivy Scan
      run: trivy image --security-checks license --severity UNKNOWN,HIGH,CRITICAL imeshdocker/dep-check:${SHORT_SHA}