name: License Check

on:
  push:
    branches:
      - main

jobs:
  license_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
  
    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Build and generate license reports
      run: |
        cd ./report/
        mvn clean package
        mvn dependency:license

    - name: Store license reports as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: license-reports
        path: ./report/
