name: Dependency License Check

on:
  push:
    branches:
      - main

jobs:
  license_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
  
    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

    # - name: Build and generate license reports
    #   run: |
    #     mvn license:third-party-report
    #     mv target report

    # - name: Store license reports as artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: license-reports
    #     path: ./report/site/

    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build & Push
      if: success()
      run: |
        docker build . -t imeshdocker/dep-check:${SHORT_SHA}
        docker push imeshdocker/dep-check:${SHORT_SHA}

    - name: Trivy Scan
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.33.0/trivy_0.33.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.33.0_Linux-64bit.deb
        trivy image --security-checks license imeshdocker/dep-check:${SHORT_SHA}